export enum WebhookEventType {
  INCIDENT_CREATED = 'INCIDENT_CREATED',
  INCIDENT_ACKNOWLEDGED = 'INCIDENT_ACKNOWLEDGED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  FALLBACK_ACTIVATED = 'FALLBACK_ACTIVATED',
  PROVIDER_DOWN = 'PROVIDER_DOWN',
  PROVIDER_RECOVERED = 'PROVIDER_RECOVERED',
  BUDGET_WARNING = 'BUDGET_WARNING',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  ERROR_RATE_HIGH = 'ERROR_RATE_HIGH',
  ADMIN_ACTION = 'ADMIN_ACTION',
}
