// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeleteCacheByKeyData, DeleteCacheData, DeleteFilterChainsByFilterChainsData, DeleteRoutesByRoutesFilterChainsByFilterChainsData, DeleteServicesByServicesFilterChainsByFilterChainsData, DeleteUpstreamsByUpstreamsTargetsByTargetsData, GetCacheByKeyData, GetCertificatesByCertificatesData, GetConfigData, GetConsumersData, GetData, GetDebugNodeLogLevelData, GetEndpointsData, GetPluginsEnabledData, GetSchemasByNameData, GetSchemasPluginsByNameData, GetStatusData, GetTagsByTagsData, GetTimersData, GetUpstreamsByUpstreamsHealthData, GetUpstreamsByUpstreamsTargetsAllData, GetUpstreamsByUpstreamsTargetsByTargetsData, GetUpstreamsByUpstreamsTargetsData, PatchCertificatesByCertificatesData, PatchConsumersByConsumersPluginsByPluginsData, PatchFilterChainsByFilterChainsData, PatchPluginsByPluginsData, PatchRoutesByRoutesFilterChainsByFilterChainsData, PatchRoutesByRoutesPluginsByPluginsData, PatchServicesByServicesFilterChainsByFilterChainsData, PatchServicesServicesPluginsPluginsData, PatchUpstreamsByUpstreamsTargetsByTargetsData, PostConfigData, PostConsumersByConsumersPluginsData, PostFilterChainsData, PostPluginsData, PostRoutesByRoutesFilterChainsData, PostRoutesByRoutesPluginsData, PostSchemasByDbEntityNameValidateData, PostSchemasPluginsValidateData, PostServicesByServicesFilterChainsData, PostServicesByServicesPluginsData, PostUpstreamsByUpstreamsTargetsData, PutCertificatesByCertificatesData, PutDebugClusterLogLevelByLogLevelData, PutDebugNodeLogLevelByLogLevelData, PutUpstreamsByUpstreamsTargetsByTargetsByAddressHealthyData, PutUpstreamsByUpstreamsTargetsByTargetsByAddressUnhealthyData, PutUpstreamsByUpstreamsTargetsByTargetsData, PutUpstreamsByUpstreamsTargetsByTargetsHealthyData, PutUpstreamsByUpstreamsTargetsByTargetsUnhealthyData } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Validate a configuration against a schema
 *
 * This method is not available when using DB-less mode.
 */
export const postSchemasByDbEntityNameValidate = <ThrowOnError extends boolean = false>(options?: Options<PostSchemasByDbEntityNameValidateData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/schemas/{db_entity_name}/validate', ...options });

export const getCertificatesByCertificates = <ThrowOnError extends boolean = false>(options?: Options<GetCertificatesByCertificatesData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/certificates/{certificates}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchCertificatesByCertificates = <ThrowOnError extends boolean = false>(options?: Options<PatchCertificatesByCertificatesData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/certificates/{certificates}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const putCertificatesByCertificates = <ThrowOnError extends boolean = false>(options?: Options<PutCertificatesByCertificatesData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/certificates/{certificates}', ...options });

/**
 * Retrieve node log level of a node
 */
export const getDebugNodeLogLevel = <ThrowOnError extends boolean = false>(options?: Options<GetDebugNodeLogLevelData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/debug/node/log-level', ...options });

/**
 * Show Upstream health for node
 */
export const getUpstreamsByUpstreamsHealth = <ThrowOnError extends boolean = false>(options?: Options<GetUpstreamsByUpstreamsHealthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/health', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postConsumersByConsumersPlugins = <ThrowOnError extends boolean = false>(options?: Options<PostConsumersByConsumersPluginsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/consumers/{consumers}/plugins', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postServicesByServicesPlugins = <ThrowOnError extends boolean = false>(options?: Options<PostServicesByServicesPluginsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/services/{services}/plugins', ...options });

/**
 * Retrieve Plugin Schema
 */
export const getSchemasPluginsByName = <ThrowOnError extends boolean = false>(options?: Options<GetSchemasPluginsByNameData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/schemas/plugins/{name}', ...options });

/**
 * List all Targets
 */
export const getUpstreamsByUpstreamsTargetsAll = <ThrowOnError extends boolean = false>(options?: Options<GetUpstreamsByUpstreamsTargetsAllData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/all', ...options });

/**
 * Retrieve Entity Schema
 */
export const getSchemasByName = <ThrowOnError extends boolean = false>(options?: Options<GetSchemasByNameData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/schemas/{name}', ...options });

/**
 * Retrieve Enabled Plugins
 */
export const getPluginsEnabled = <ThrowOnError extends boolean = false>(options?: Options<GetPluginsEnabledData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/plugins/enabled', ...options });

/**
 *  List entity IDs by tag
 */
export const getTagsByTags = <ThrowOnError extends boolean = false>(options?: Options<GetTagsByTagsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/tags/{tags}', ...options });

/**
 * List available endpoints
 */
export const getEndpoints = <ThrowOnError extends boolean = false>(options?: Options<GetEndpointsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/endpoints', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchPluginsByPlugins = <ThrowOnError extends boolean = false>(options?: Options<PatchPluginsByPluginsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/plugins/{plugins}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postRoutesByRoutesPlugins = <ThrowOnError extends boolean = false>(options?: Options<PostRoutesByRoutesPluginsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/routes/{routes}/plugins', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const deleteCache = <ThrowOnError extends boolean = false>(options?: Options<DeleteCacheData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/cache', ...options });

export const patchServicesServicesPluginsPlugins = <ThrowOnError extends boolean = false>(options?: Options<PatchServicesServicesPluginsPluginsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/services/:services/plugins/:plugins', ...options });

export const getConsumers = <ThrowOnError extends boolean = false>(options?: Options<GetConsumersData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/consumers', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchConsumersByConsumersPluginsByPlugins = <ThrowOnError extends boolean = false>(options?: Options<PatchConsumersByConsumersPluginsByPluginsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/consumers/{consumers}/plugins/{plugins}', ...options });

/**
 * Delete Target
 *
 * This method is not available when using DB-less mode.
 */
export const deleteUpstreamsByUpstreamsTargetsByTargets = <ThrowOnError extends boolean = false>(options?: Options<DeleteUpstreamsByUpstreamsTargetsByTargetsData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}', ...options });

export const getUpstreamsByUpstreamsTargetsByTargets = <ThrowOnError extends boolean = false>(options?: Options<GetUpstreamsByUpstreamsTargetsByTargetsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}', ...options });

/**
 * Update Target
 *
 * This method is not available when using DB-less mode.
 */
export const patchUpstreamsByUpstreamsTargetsByTargets = <ThrowOnError extends boolean = false>(options?: Options<PatchUpstreamsByUpstreamsTargetsByTargetsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const putUpstreamsByUpstreamsTargetsByTargets = <ThrowOnError extends boolean = false>(options?: Options<PutUpstreamsByUpstreamsTargetsByTargetsData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}', ...options });

/**
 * Set target as healthy
 *
 * This method is not available when using DB-less mode.
 */
export const putUpstreamsByUpstreamsTargetsByTargetsHealthy = <ThrowOnError extends boolean = false>(options?: Options<PutUpstreamsByUpstreamsTargetsByTargetsHealthyData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}/healthy', ...options });

/**
 * Set log level of a single node
 *
 * This method is not available when using DB-less mode.
 */
export const putDebugNodeLogLevelByLogLevel = <ThrowOnError extends boolean = false>(options?: Options<PutDebugNodeLogLevelByLogLevelData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/debug/node/log-level/{log_level}', ...options });

/**
 * Set target address as unhealthy
 *
 * This method is not available when using DB-less mode.
 */
export const putUpstreamsByUpstreamsTargetsByTargetsByAddressUnhealthy = <ThrowOnError extends boolean = false>(options?: Options<PutUpstreamsByUpstreamsTargetsByTargetsByAddressUnhealthyData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}/{address}/unhealthy', ...options });

/**
 * Set target as unhealthy
 *
 * This method is not available when using DB-less mode.
 */
export const putUpstreamsByUpstreamsTargetsByTargetsUnhealthy = <ThrowOnError extends boolean = false>(options?: Options<PutUpstreamsByUpstreamsTargetsByTargetsUnhealthyData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}/unhealthy', ...options });

export const getUpstreamsByUpstreamsTargets = <ThrowOnError extends boolean = false>(options?: Options<GetUpstreamsByUpstreamsTargetsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postUpstreamsByUpstreamsTargets = <ThrowOnError extends boolean = false>(options?: Options<PostUpstreamsByUpstreamsTargetsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets', ...options });

/**
 * Set target address as healthy
 *
 * This method is not available when using DB-less mode.
 */
export const putUpstreamsByUpstreamsTargetsByTargetsByAddressHealthy = <ThrowOnError extends boolean = false>(options?: Options<PutUpstreamsByUpstreamsTargetsByTargetsByAddressHealthyData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/upstreams/{upstreams}/targets/{targets}/{address}/healthy', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const deleteCacheByKey = <ThrowOnError extends boolean = false>(options?: Options<DeleteCacheByKeyData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/cache/{key}', ...options });

export const getCacheByKey = <ThrowOnError extends boolean = false>(options?: Options<GetCacheByKeyData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/cache/{key}', ...options });

/**
 * Retrieve node information
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Set node log level of all nodes
 *
 * This method is not available when using DB-less mode.
 */
export const putDebugClusterLogLevelByLogLevel = <ThrowOnError extends boolean = false>(options?: Options<PutDebugClusterLogLevelByLogLevelData, ThrowOnError>) => (options?.client ?? client).put<unknown, unknown, ThrowOnError>({ url: '/debug/cluster/log-level/{log_level}', ...options });

/**
 * Validate a plugin configuration against the schema
 *
 * This method is not available when using DB-less mode.
 */
export const postSchemasPluginsValidate = <ThrowOnError extends boolean = false>(options?: Options<PostSchemasPluginsValidateData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/schemas/plugins/validate', ...options });

/**
 * Retrieve runtime debugging info of Kong's timers
 */
export const getTimers = <ThrowOnError extends boolean = false>(options?: Options<GetTimersData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/timers', ...options });

/**
 * Retrieve node status
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postPlugins = <ThrowOnError extends boolean = false>(options?: Options<PostPluginsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/plugins', ...options });

/**
 * This method is only available when using DB-less mode.
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/config', ...options });

/**
 * This method is only available when using DB-less mode.
 */
export const postConfig = <ThrowOnError extends boolean = false>(options?: Options<PostConfigData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/config', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchRoutesByRoutesPluginsByPlugins = <ThrowOnError extends boolean = false>(options?: Options<PatchRoutesByRoutesPluginsByPluginsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/routes/{routes}/plugins/{plugins}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PostFilterChainsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/filter-chains', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const deleteFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<DeleteFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/filter-chains/{filter_chains}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PatchFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/filter-chains/{filter_chains}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postServicesByServicesFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PostServicesByServicesFilterChainsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/services/{services}/filter-chains', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const deleteServicesByServicesFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<DeleteServicesByServicesFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/services/{services}/filter-chains/{filter_chains}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchServicesByServicesFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PatchServicesByServicesFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/services/{services}/filter-chains/{filter_chains}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const postRoutesByRoutesFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PostRoutesByRoutesFilterChainsData, ThrowOnError>) => (options?.client ?? client).post<unknown, unknown, ThrowOnError>({ url: '/routes/{routes}/filter-chains', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const deleteRoutesByRoutesFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<DeleteRoutesByRoutesFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/routes/{routes}/filter-chains/{filter_chains}', ...options });

/**
 * This method is not available when using DB-less mode.
 */
export const patchRoutesByRoutesFilterChainsByFilterChains = <ThrowOnError extends boolean = false>(options?: Options<PatchRoutesByRoutesFilterChainsByFilterChainsData, ThrowOnError>) => (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({ url: '/routes/{routes}/filter-chains/{filter_chains}', ...options });
