// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8001' | 'https://localhost:8444' | (string & {});
};

export type KeySets = {
  id?: string;
  tags?: Array<unknown>;
  name?: string;
  created_at?: number;
  updated_at?: number;
};

export type ClusteringDataPlanes = {
  version?: string;
  last_seen?: number;
  config_hash?: string;
  sync_status: string;
  id: string;
  updated_at?: number;
  hostname: string;
  ip: string;
};

export type Parameters = {
  value: string;
  created_at?: number;
  key: string;
};

export type Plugins = {
  config?: Array<unknown>;
  consumer?: Consumers;
  enabled: boolean;
  protocols: 'http' | 'https' | 'tcp' | 'tls' | 'udp' | 'grpc' | 'grpcs';
  instance_name?: string;
  id?: string;
  tags?: Array<unknown>;
  updated_at?: number;
  name: string;
  route?: Routes;
  created_at?: number;
  service?: Services;
};

export type Tags = {
  entity_name: string;
  entity_id: string;
  tag: string;
};

export type Services = {
  retries?: number;
  connect_timeout?: number;
  tags?: Array<unknown>;
  write_timeout?: number;
  read_timeout?: number;
  created_at?: number;
  client_certificate?: Certificates;
  protocol: string;
  tls_verify_depth?: number;
  host: string;
  port: number;
  enabled: boolean;
  ca_certificates?: Array<unknown>;
  updated_at?: number;
  id?: string;
  path?: string;
  name?: string;
  tls_verify?: boolean;
};

export type Routes = {
  strip_path: boolean;
  https_redirect_status_code: number;
  path_handling?: string;
  hosts?: Array<unknown>;
  methods?: Array<unknown>;
  paths?: unknown;
  protocols: Array<unknown>;
  sources?: Array<unknown>;
  id?: string;
  tags?: Array<unknown>;
  created_at?: number;
  updated_at?: number;
  headers?: Array<unknown>;
  regex_priority?: number;
  preserve_host: boolean;
  destinations?: Array<unknown>;
  request_buffering: boolean;
  snis?: Array<unknown>;
  response_buffering: boolean;
  name?: string;
  service?: Services;
};

export type Consumers = {
  custom_id?: string;
  id?: string;
  tags?: Array<unknown>;
  username?: string;
  created_at?: number;
  updated_at?: number;
};

export type Workspaces = {
  id?: string;
  config?: Array<unknown>;
  meta?: Array<unknown>;
  name: string;
  comment?: string;
  created_at?: number;
  updated_at?: number;
};

export type Certificates = {
  key_alt?: string;
  id?: string;
  tags?: Array<unknown>;
  key: string;
  cert_alt?: string;
  updated_at?: number;
  created_at?: number;
  cert: string;
};

export type CaCertificates = {
  id?: string;
  tags?: Array<unknown>;
  cert_digest?: string;
  updated_at?: number;
  created_at?: number;
  cert: string;
};

export type Snis = {
  id?: string;
  tags?: Array<unknown>;
  certificate: Certificates;
  name: string;
  created_at?: number;
  updated_at?: number;
};

export type Upstreams = {
  hash_on?: string;
  hash_fallback?: string;
  hash_on_header?: string;
  hash_fallback_header?: string;
  id?: string;
  tags?: Array<unknown>;
  hash_on_cookie_path?: string;
  hash_on_query_arg?: string;
  created_at?: number;
  hash_fallback_query_arg?: string;
  hash_on_uri_capture?: string;
  hash_fallback_uri_capture?: string;
  host_header?: string;
  use_srv_name?: boolean;
  client_certificate?: Certificates;
  healthchecks?: Array<unknown>;
  hash_on_cookie?: string;
  updated_at?: number;
  slots?: number;
  name: string;
  algorithm?: string;
};

export type Targets = {
  weight?: number;
  id?: string;
  tags?: Array<unknown>;
  upstream: Upstreams;
  target: string;
  created_at?: number;
  updated_at?: number;
};

export type Vaults = {
  description?: string;
  id?: string;
  prefix: string;
  tags?: Array<unknown>;
  config?: Array<unknown>;
  created_at?: number;
  name: string;
  updated_at?: number;
};

export type Keys = {
  kid: string;
  jwk?: string;
  id?: string;
  tags?: Array<unknown>;
  pem?: unknown;
  set?: KeySets;
  name?: string;
  created_at?: number;
  updated_at?: number;
};

export type FilterChains = {
  id?: string;
  name?: string;
  enabled?: boolean;
  filters?: Array<Filters>;
  service?: Services;
  route?: Routes;
  tags?: Array<unknown>;
  created_at?: number;
  updated_at?: number;
};

export type Filters = {
  name: string;
  config?: string;
  enabled?: boolean;
};

export type PostSchemasByDbEntityNameValidateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/schemas/{db_entity_name}/validate';
};

export type GetCertificatesByCertificatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/certificates/{certificates}';
};

export type PatchCertificatesByCertificatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/certificates/{certificates}';
};

export type PutCertificatesByCertificatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/certificates/{certificates}';
};

export type GetDebugNodeLogLevelData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/debug/node/log-level';
};

export type GetUpstreamsByUpstreamsHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/health';
};

export type PostConsumersByConsumersPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/consumers/{consumers}/plugins';
};

export type PostServicesByServicesPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/services/{services}/plugins';
};

export type GetSchemasPluginsByNameData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/schemas/plugins/{name}';
};

export type GetUpstreamsByUpstreamsTargetsAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/all';
};

export type GetSchemasByNameData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/schemas/{name}';
};

export type GetPluginsEnabledData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/plugins/enabled';
};

export type GetTagsByTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tags/{tags}';
};

export type GetEndpointsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/endpoints';
};

export type PatchPluginsByPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/plugins/{plugins}';
};

export type PostRoutesByRoutesPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/routes/{routes}/plugins';
};

export type DeleteCacheData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/cache';
};

export type PatchServicesServicesPluginsPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/services/:services/plugins/:plugins';
};

export type GetConsumersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/consumers';
};

export type PatchConsumersByConsumersPluginsByPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/consumers/{consumers}/plugins/{plugins}';
};

export type DeleteUpstreamsByUpstreamsTargetsByTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}';
};

export type GetUpstreamsByUpstreamsTargetsByTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}';
};

export type PatchUpstreamsByUpstreamsTargetsByTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}';
};

export type PutUpstreamsByUpstreamsTargetsByTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}';
};

export type PutUpstreamsByUpstreamsTargetsByTargetsHealthyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}/healthy';
};

export type PutDebugNodeLogLevelByLogLevelData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/debug/node/log-level/{log_level}';
};

export type PutUpstreamsByUpstreamsTargetsByTargetsByAddressUnhealthyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}/{address}/unhealthy';
};

export type PutUpstreamsByUpstreamsTargetsByTargetsUnhealthyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}/unhealthy';
};

export type GetUpstreamsByUpstreamsTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets';
};

export type PostUpstreamsByUpstreamsTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets';
};

export type PutUpstreamsByUpstreamsTargetsByTargetsByAddressHealthyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/upstreams/{upstreams}/targets/{targets}/{address}/healthy';
};

export type DeleteCacheByKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/cache/{key}';
};

export type GetCacheByKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/cache/{key}';
};

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type PutDebugClusterLogLevelByLogLevelData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/debug/cluster/log-level/{log_level}';
};

export type PostSchemasPluginsValidateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/schemas/plugins/validate';
};

export type GetTimersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/timers';
};

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/status';
};

export type PostPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/plugins';
};

export type GetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/config';
};

export type PostConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/config';
};

export type PatchRoutesByRoutesPluginsByPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/routes/{routes}/plugins/{plugins}';
};

export type PostFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/filter-chains';
};

export type DeleteFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/filter-chains/{filter_chains}';
};

export type PatchFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/filter-chains/{filter_chains}';
};

export type PostServicesByServicesFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/services/{services}/filter-chains';
};

export type DeleteServicesByServicesFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/services/{services}/filter-chains/{filter_chains}';
};

export type PatchServicesByServicesFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/services/{services}/filter-chains/{filter_chains}';
};

export type PostRoutesByRoutesFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/routes/{routes}/filter-chains';
};

export type DeleteRoutesByRoutesFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/routes/{routes}/filter-chains/{filter_chains}';
};

export type PatchRoutesByRoutesFilterChainsByFilterChainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/routes/{routes}/filter-chains/{filter_chains}';
};
